---
title: "Education & Experience"
---
  
<br>
  
## Education
  
September 2025: PhD candidate, CTS program, CWRU
November 2022: Certificate in Mastering the business of Orthodontics, from Wharton
Online, University of Pennsylvania in collaboration with the AAO.
2016-2018: Orthodontic Residency and Master of Dental Science, Case Western Reserve
University, Cleveland OH
2015-2016: Fellowship in Orthodontics, Case Western Reserve University, Cleveland OH
2009-2012: Master of Dental Science in Operative Dentistry, Faculty of Oral and Dental
Medicine, Cairo University, Cairo Egypt
2001-2006: Bachelor of Dental Science, Faculty of Oral and Dental Medicine, Cairo
University, Cairo Egypt
... 

---
  
  
## Professional Experience
June 2025: Owner/Orthodontist of Orabi Orthodontics
January 2023-Present: Co-Director of Early Treatment Clinic, Orthodontic department, Case Western Reserve University
June 2021-Present: Clinical Assistant Professor, Orthodontic department, Case Western Reserve University
February 2019-April 2025: Orthodontist at Wenger Orthodontics, Cleveland, OH
Jan 2013- December 2013: Associate researcher in “Tooth structure defects and contributing factors” project, a combined project between Queen Medical and Cairo University.
February 2013- Present: Assistant lecturer in Operative department, Faculty of Oral and Dental Medicine, Cairo University
2008-2012: Resident / Demonstrator in Restorative Dentistry department, Faculty of Oral and Dental Medicine, Cairo University
2007-2008: Resident in Orthodontic department, Faculty of Oral and Dental Medicine, Cairo   University
2006-2007:  Internship, Faculty of Oral and Dental Medicine, Cairo University

---
  
  
## Research Experience
  
1-Master’s Thesis 2018: Effect of orthodontic treatment aiming at sagittal changes on the upper airway: A systematic review and Meta-analysis
2-Master’s Thesis 2012: Antibacterial Effect, Elemental composition and Bond Strength of Nanoparticles incorporated into Dentin Adhesive

3-Associate researcher 2013-2014: Qatar-Egypt project collaboration between Queen medical research office and Cairo University funded by Qatar national research foundation “The link between tooth structure defects and contributing factors”.

## Publications

1-Noha G Orabi, Carlos Flores-Mir, Tarek Elshebiny, Sherif Elkordy, and Juan Martin Palomo : “Pharyngeal airway dimensional changes after orthodontic treatment with premolar extractions: A systematic review with meta-analysis”,  2021 Oct;160(4):503-515

2- Noha G Orabi, Faisal Quereshy, Tarek Elshebiny, Mansih valiathan : An Alternative Approach for Treatment of Impacted Teeth : Autotranspantation of an Impacted Central Incisor, a Three year Follow-up : JCO In-Press

3-Ahmed ElKhadem and Noha Orabi. Weak evidence suggests higher risk for bracket bonding failure with self-etch primer compared to conventional acid etch over 12 months. Evidence-Based Dentistry 2013:14.2, 52-53. 

4-Noha Orabi, Ahmed El-Zoheiry, and Mohamed Abdel-Mohsen. Effect of different concentrations of Silver Nanoparticles dispersed in Ethanol on Sreptococcus Mutans, Cairo. Dental Journal 2013:29.1, 173-177.
ORAL PRESENTATIONS:



ABSTRACTS:

1-Accepted Abstract at ACPA 2019 # 322: Noha G Orabi, Faisal Quereshy, Sherif Morcos, Anand Kumar, Manish Valiathan: Auto-transplantation in the Management of Topoth Agenesis in Cleft Lip and Palate Patient

2-Accepted Abstracts at AAO 2019: Sherif Morcos, Noha G Orabi, Konstantinos Apostolopoulos, J M. Palomo: Transverse Dento-alveolar Changes Using Orthodontic Passive Self-Ligating System. A pilot Retrospective CBCT Study

3-Accepted Abstract at AAO 2018: Noha.G Orabi, Tarek El-Shebiny, J. M
Palomo: Comparison between 2D Traditional Superimposition and 3D Voxel-based
Superimposition

4- Qatar Foundation Annual Research Forum Proceedings 2013, BIOP 0166
Elham Mostafa Fawzi, Hussni O. Mahammed, Noha Orabi, Mahmoud A. Mahmoud, Mohamed M. Al Bashbishi. Oral Health Status In Qatar And Egypt: An Approach to Develop a Novel Index for Different Tooth Structure Defects. 

---
  
## Download My CV
  
**[Click here to download my full CV](cv.pdf)**